### ISSUE TITLE
hello everyone

### ISSUE THREAD

**Issue by UNIvErSeKO** [LobbyDivinus/theotown-translation#140]
sorry, sorry, sorry. 
I busy Korean school. so, me and team nose-cone is can't touch this translate. but some people help this translation. 
thank you.
and we start In the near future may be... 2-3 days?

------한국어----------
팀 노즈콘 (임시) 팀장입니다. 번역팀의 상황이 좋지 못했던 관계로 이 번역물을 건드리지 못했는데.
이렇게 다른 분이 오셔서 (어쩌면 같은 팀인데 서로 모를지도 모르겠습니다만) 도와 주시니 참으로 감사드립니다. 나머지 부분은 저희 팀에서 처리하겠습니다. 좋은 하루 보내시길 :D

**Comment by LobbyDivinus** [comment]
Thank you for your effort :)

**Comment by yvelkram** [comment]
(To UNIvErSeKo)
 무려 6달동안 아무런 이유없이 잠수타셨었습니다.(로비님이 소식이 끊겼다고 했습니다.) 하도 답답해서 대신하게되었는데 갑자기 이렇게 오시니 조금 당황스럽긴합니다.
 번역하는사람이 많으면 저야 좋긴하지요. 그러나, 현재로서는 신튜토리얼, 기타 귀찮은 부분을 않하다가 누가 번역하니 그 자리를 빼앗는 느낌이 들어 조금 기분이 나쁘긴 하네요.

 만일 오해라면 해명 부탁드립니다.

**Comment by UNIvErSeKO** [comment]
죄송합니다, 진짜로 생각해보니 아무런 말도 없이 잠수를 탔었군요.
그동안에 저희 팀은 분해의 위기에 처한게 하나 둘이 아니었었기 때문에, 이리저리 신경쓰느라 들어오는것도 잊고 있었습니다.. 죄송합니다ㅠ
번역하시는것에 대해서는 뭐라고 하지 않겠습니다. 기분이 나쁘셨다면 사과드리겠습니다. 
약간 한국 사정에 맞게 (예를 들어 레딧) 바꿔서 번역한 면이 몆가지 있었는데 매우 부드럽게 다듬어 주신걸 보고 '이분 진심이시구나' 라고 생각했습니다, 저의 언동으로 인해서 혹시나 상처 받으신 부분이 있으시다면 다시 한번 사과드리겠습니다. 앞으로는 같이 번역하시죠.
물론 그렇다고 팀-노즈콘으로 들어오시라고 이야기 하는건 아닙니다만. 원래 협업이 제일 좋은거잖습니까

**Comment by yvelkram** [comment]
우선 말이 너무 심했다면 사과드립니다.
 작년 9월부터 친구랑 같이하게 되었는데 공통적으로 번역이 조금 않맞다는 의견이 있었습니다. 그래서 하는김에 원문에 충실하자 해서 대부분 뜯어고쳤습니다. 번역이아니라 Re-translation이라 한 의유이기도합니다.
 방금 마지막 번역이 끝났고 이제 조금씩 손보기만 하면 됩니다.  물론 어느정도 활동적이게 하는것도 좋고 저도 그렇게 하나, 드립이 너무 주제를 벋어나지 않았으면 하는것이 제 바렘입니다. 감자드립은 토네이도와 발음이 비슷하신것에서 생각하신듯 한데 한국인입장에서는 이해가 힘든점도 있습니다. 이경우 오히려
 욕먹을수도 있습니다. 그런점 제외하고는 있으면 좋지요.
 가능하면 앞으로 구플이나 커뮤니티에서 충돌에 대해서 상의할수 있으면 좋겠습니다.

 너무말이 심했다면 죄송합니다.

 나머지부분에 대해서도 적용되면 수정하도록 하겠습니다

**Comment by UNIvErSeKO** [comment]
아. 답뱐 감사드립니다. 다만 저도 Theotown을 약 1년정도 넘게 플레이를 하고 있습니다.
다만 몆몆 오역이 있었던건 인정하겠습니다. 
도를 넘은 드립도 사과드리겠습니다. 워낙에 이전 게임에서 (KSP를 번역했었지만. 글자 출력 방식의 문제로 그만뒀죠) 심즈급 병맛 번역이라는 이야기를 들은지나 너무 마음이 앞선듯 싶었습니다.
다행히도 번역팀은 반쪼각이지만 다행히도 유지중입니다. 요즘은 유튜브 영상계열로 번역이 좀 옮겨가는 추세라, 이후 게임에대한 번역은 팀 전체가 아니라 제가 개인적으로 하게 될 듯 싶네요. 
(솔직히 제일 아쉬운게 번역에 참가한 번역자 이름을 레딧로딩 문구대신에 바꿔둔걸 다시 바꿔두셔서 아쉽...읍!)

**Comment by UNIvErSeKO** [comment]
저도 참고로 이야기 해드리자면, 과거 버전의 맵에 대해서 고대 도시보다도 옛버전 도시가 좀더 자연스헙습니다
