### ISSUE TITLE
How active this translate?

### ISSUE THREAD

**Issue by UNIvErSeKO** [LobbyDivinus/theotown-translation#2]
Hello. I'm korean translate team. 
We translate for google docs, and reallly fast translate. 
But. We chack translate. Than. How active translate. Computer is good. But. We want active for phone

**Comment by HernanGaitan585** [comment]
forgiveness, not speak very well English, but not I can "understand" your question,

**Comment by UNIvErSeKO** [comment]
Oh...sorry. to sum it up, how to apply translate?
We team test this.

**Comment by LobbyDivinus** [comment]
By starting a pull request as you did, that's fine :)

**Comment by UNIvErSeKO** [comment]
Thanks
