### ISSUE TITLE
Game closes :(

### ISSUE THREAD

**Issue by HernanGaitan585** [LobbyDivinus/theotown-translation#26]
I open the game, I create a city and when I create the city (the city is shown) it closes.
If you load a city it also closes :(
I leave you a demo video:
[https://www.youtube.com/watch?v=09sTdGyLx78](url)

I also leave you the specifications of my tablet:
Brand: CX.
Model: CX9005.
Processor: All Winner Quad-Code.
Android: 4.4.

**Comment by LobbyDivinus** [comment]
I have not access to the video :/
