### ISSUE TITLE
How do I play in the Spanish language?

### ISSUE THREAD

**Issue by HernanGaitan585** [LobbyDivinus/theotown-translation#5]
Should I wait to update the app, or just have to activate something?

**Comment by LobbyDivinus** [comment]
Which version do you have? If you install the apk from this repository Spanish should be available.

**Comment by HernanGaitan585** [comment]
I have the version: beta 1.1.87.
-Hernan

**Comment by HernanGaitan585** [comment]
I have already solved it. Sorry for the inconvenience, I'm new to this.
-Hernan.
