### ISSUE TITLE
Wrong Supply Number needed in DSA translations

### ISSUE THREAD

**Issue by KamikaziF** [LobbyDivinus/theotown-translation#572]
As the title says, some DSA Supply numbers are wrong/outdated, leading to confuse people because they have that x wrong supply number and asking what is wrong, and it's simply it has the wrong number displayed. So if you can, please fux this issue ASAP
Here is an example image of the issue.
![Misstranslated text](https://user-images.githubusercontent.com/38037802/104946885-1b7f0e00-59bb-11eb-9f01-8cef27e75879.png)

**Comment by JustAnyones** [comment]
They are not hardcoded
https://github.com/LobbyDivinus/theotown-translation/blob/master/dsa/default.json#L135
https://github.com/LobbyDivinus/theotown-translation/blob/master/dsa/spanish.json#L135
https://github.com/LobbyDivinus/theotown-translation/blob/master/dsa/polish.json#L130

**Comment by KamikaziF** [comment]
Whoops, looks like i didn't search properly enough. Anyways, i'm going to leave this so translators can take notice of this issue
