### ISSUE TITLE
Can someone update the apk?

### ISSUE THREAD

**Issue by BYXxiaonanhui** [LobbyDivinus/theotown-translation#582]
Can someone update the apk, PLEASE?
I couldn't use Google Play for some reasons, so I depend on Github to get the newest version. I also request the newest version for my friend.
The apk here is 1.9.54, updated 3 months ago...

**Comment by BYXxiaonanhui** [comment]
@JustAnyones Anyone there?

**Comment by JustAnyones** [comment]
Game is not yet in release version.
