### ISSUE TITLE
Potential future problem related to ci_loan_get_text

### ISSUE THREAD

**Issue by JustAnyones** [LobbyDivinus/theotown-translation#607]
There is a potential issue related to the loan description. It is not future proof. Any changes of these internally values would break the translation for many different languages by becoming misleading. It would be much better to use string interpolation here.

https://github.com/LobbyDivinus/theotown-translation/blob/90a661e8b741b807d7bc6dc994c096635c758aac/values/strings.xml#L499-L501

**Comment by LobbyDivinus** [comment]
yes

**Comment by LobbyDivinus** [comment]
Actually, ci_loan_get_text is not in use anymore, it was replaced by ci_loan_get_text2 which features string formatting parameters.
